export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST ='REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';
export const VERIFICATION_START = 'VERIFICATION_START';

export const INTEREST_SUCCESS = 'INTEREST_SUCCESS';
export const INTEREST_FAILURE = 'INTEREST_FAILURE';
export const INTEREST_START = 'INTEREST_START';