export const TOGGLE_MODAL = "TOGGLE_MODAL"
export const PUBLISHING_START = "PUBLISHING_START"
export const PUBLISHING_FAIL = "PUBLISHING_FAIL"
export const PUBLISHING_SUCCESS = "PUBLISHING_SUCCESS"
export const SAVING_START = "SAVING_START"
export const SAVING_FAIL = "SAVING_FAIL"
export const SAVING_SUCCESS = "SAVING_SUCCESS"
export const ADD_TAG = "ADD_TAG"
export const REMOVE_TAG = "REMOVE_TAG"
export const LOAD_TAGS = "LOAD_TAGS"

export const GET_ALL_ARTICLES_START = "GET_ALL_ARTICLES_START";
export const GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS";
export const GET_ALL_ARTICLES_FAIL = "GET_ALL_ARTICLES_FAIL";


export const GET_SINGLE_START = "GET_SINGLE_START";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL";

export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_FAILURE = "GET_ALL_NOTIFICATIONS_FAILURE";

export const GET_SINGLE_NOTIFICATION = "GET_SINGLE_NOTIFICATION";
export const GET_SINGLE_NOTIFICATION_SUCCESS = "GET_SINGLE_NOTIFICATION_SUCCESS";
export const GET_SINGLE_NOTIFICATION_FAILURE = "GET_SINGLE_NOTIFICATION_FAILURE";