export const TOGGLE_MODAL = "TOGGLE_MODAL"
export const PUBLISHING_START = "PUBLISHING_START"
export const PUBLISHING_FAIL = "PUBLISHING_FAIL"
export const PUBLISHING_SUCCESS = "PUBLISHING_SUCCESS"
export const SAVING_START = "SAVING_START"
export const SAVING_FAIL = "SAVING_FAIL"
export const SAVING_SUCCESS = "SAVING_SUCCESS"
export const ADD_TAG = "ADD_TAG"
export const REMOVE_TAG = "REMOVE_TAG"
export const LOAD_TAGS = "LOAD_TAGS"

export const GET_ALL_ARTICLES_START = "GET_ALL_ARTICLES_START";
export const GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS";
export const GET_ALL_ARTICLES_FAIL = "GET_ALL_ARTICLES_FAIL";

export const GET_SINGLE_START = "GET_SINGLE_START";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL";

export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const UPDATE_USER_PROFILE_START = "UPDATE_USER_PROFILE_START";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

export const GET_TAGS_START = "GET_TAGS_START";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAIL = "GET_TAGS_FAIL";

export const UPDATE_USER_INTERESTS_START = "UPDATE_USER_INTERESTS_START";
export const REMOVE_USER_INTERESTS_SUCCESS = "REMOVE_USER_INTERESTS_SUCCESS";
export const ADD_USER_INTERESTS_SUCCESS = "ADD_USER_INTERESTS_SUCCESS";
export const UPDATE_USER_INTERESTS_FAIL = "UPDATE_USER_INTERESTS_FAIL";

export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_FAILURE = "GET_ALL_NOTIFICATIONS_FAILURE";

export const GET_SINGLE_NOTIFICATION = "GET_SINGLE_NOTIFICATION";
export const GET_SINGLE_NOTIFICATION_SUCCESS = "GET_SINGLE_NOTIFICATION_SUCCESS";
export const GET_SINGLE_NOTIFICATION_FAILURE = "GET_SINGLE_NOTIFICATION_FAILURE";
export const GET_USER_ARTICLES_START = "GET_USER_ARTICLES_START";
export const GET_USER_ARTICLES_SUCCESS = "GET_USER_ARTICLES_SUCCESS";
export const GET_USER_ARTICLES_FAIL = "GET_USER_ARTICLES_FAIL";

export const GET_USER_ARTICLES_DRAFT_START = "GET_USER_ARTICLES_DRAFT_START";
export const GET_USER_ARTICLES_DRAFT_SUCCESS = "GET_USER_ARTICLES_DRAFT_SUCCESS";
export const GET_USER_ARTICLES_DRAFT_FAIL = "GET_USER_ARTICLES_DRAFT_FAIL";


export const DELETE_USER_ARTICLES_START = "DELETE_USER_ARTICLES_START";
export const DELETE_USER_ARTICLES_SUCCESS = "DELETE_USER_ARTICLES_SUCCESS";
export const DELETE_USER_ARTICLES_FAIL = "DELETE_USER_ARTICLES_FAIL";
export const GET_ALL_TAGS_START = "GET_ALL_TAGS_START";
export const GET_ALL_TAGS_SUCCESS = "GET_ALL_TAGS_SUCCESS";
export const GET_ALL_TAGS_FAIL = "GET_ALL_TAGS_FAIL";

export const GET_USERS_TO_FOLLOW_START = "GET_USERS_TO_FOLLOW_START";
export const GET_USERS_TO_FOLLOW_SUCCESS = "GET_USERS_TO_FOLLOW_SUCCESS";
export const GET_USERS_TO_FOLLOW_FAIL = "GET_USERS_TO_FOLLOW_FAIL";

export const FOLLOW_USERS_START = "FOLLOW_USERS_START";
export const FOLLOW_USERS_SUCCESS = "FOLLOW_USERS_SUCCESS";
export const FOLLOW_USERS_FAIL = "FOLLOW_USERS_FAIL";
export const GET_AUTHOR_PROFILE_START = "GET_AUTHOR_PROFILE_START";
export const GET_AUTHOR_PROFILE_SUCCESS = "GET_AUTHOR_PROFILE_SUCCESS";
export const GET_AUTHOR_PROFILE_FAIL = "GET_AUTHOR_PROFILE_FAIL";

export const GET_AUTHOR_ARTICLES_START = "GET_AUTHOR_ARTICLES_START";
export const GET_AUTHOR_ARTICLES_SUCCESS = "GET_AUTHOR_ARTICLES_SUCCESS";
export const GET_AUTHOR_ARTICLES_FAIL = "GET_AUTHOR_ARTICLES_FAIL";

export const FOLLOW_AUTHOR_START = "FOLLOW_AUTHOR_START";
export const FOLLOW_AUTHOR_SUCCESS = "FOLLOW_AUTHOR_SUCCESS";
export const FOLLOW_AUTHOR_FAIL = "FOLLOW_AUTHOR_FAIL";

export const GET_REACTIONS_START = "GET_REACTIONS_START";
export const GET_REACTIONS_SUCCESS = "GET_REACTIONS_SUCCESS";
export const GET_REACTIONS_FAIL = "GET_REACTIONS_FAIL";

export const GET_BASIC_INFO_SUCCESS = "GET_BASIC_INFO_SUCCESS";

export const FOLLOW_USER_START = "FOLLOW_USER_START";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";

